"""take 1m

Revision ID: 0aa4c4798eb6
Revises: 7d9af6962817
Create Date: 2023-03-05 18:02:22.582961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa4c4798eb6'
down_revision = '7d9af6962817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('livestock_breed_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('breed')
        batch_op.drop_column('classifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classifications', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('livestock_breed_key', ['breed'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
