"""livestock

Revision ID: 7d9af6962817
Revises: 508ad142f11e
Create Date: 2023-03-04 20:57:28.539296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9af6962817'
down_revision = '508ad142f11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_constraint('livestock_classifications_key', type_='unique')
        batch_op.drop_constraint('livestock_species_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.create_unique_constraint('livestock_species_key', ['species'])
        batch_op.create_unique_constraint('livestock_classifications_key', ['classifications'])

    # ### end Alembic commands ###
